# Generated by Django 5.0.7 on 2024-07-30 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cliente.cliente')),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=12)),
                ('data_nascimento', models.DateField()),
            ],
            bases=('app_cliente.cliente',),
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cliente.cliente')),
                ('cnpj', models.CharField(max_length=18)),
                ('razao_social', models.CharField(max_length=100)),
                ('inscricao_estadual', models.CharField(max_length=20)),
            ],
            bases=('app_cliente.cliente',),
        ),
    ]
