# Generated by Django 5.0.7 on 2024-07-31 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_loja', '0005_remove_cliente_user_remove_pessoafisica_cliente_ptr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('metodo_pagamento', models.CharField(choices=[('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('boleto', 'Boleto Bancário'), ('pix', 'Pix')], max_length=50)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_loja.produto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
