# Generated by Django 5.0.7 on 2024-07-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id_cliente',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='id_item_pedido',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='id_pedido',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='id_produto',
            new_name='id',
        ),
    ]
