# Generated by Django 5.0.7 on 2024-07-28 17:17

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0003_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
