# Generated by Django 5.0.7 on 2024-07-30 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cliente', '0001_initial'),
        ('app_loja', '0004_cliente_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='cliente_ptr',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cliente.cliente'),
        ),
        migrations.DeleteModel(
            name='PessoaJuridica',
        ),
        migrations.DeleteModel(
            name='PessoaFisica',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
