# Generated by Django 5.0.7 on 2024-07-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0005_remove_cliente_user_remove_pessoafisica_cliente_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='imgUrl',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='produto',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='stars',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(),
        ),
    ]
