# Generated by Django 5.0.7 on 2024-08-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0006_remove_produto_descricao_remove_produto_estoque_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='stars',
        ),
    ]
