# Generated by Django 5.0.7 on 2024-08-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0007_remove_produto_reviews_remove_produto_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='produto',
            name='subcategoria',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
