# Generated by Django 5.0.7 on 2024-08-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0007_remove_produto_reviews_remove_produto_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='categoria',
            new_name='subcategoria',
        ),
    ]
