# Generated by Django 5.0.7 on 2024-08-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0008_rename_categoria_produto_subcategoria'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produto',
            table='Produto',
        ),
    ]
