# Generated by Django 5.0.7 on 2024-08-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0009_alter_produto_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imgUrl',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='subcategoria',
            field=models.CharField(max_length=100),
        ),
    ]
